/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.glavna;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JMenuItem;

/**
 *
 * @author student1
 */
public class FmGlavna extends javax.swing.JFrame {

    /**
     * Creates new form FmGlavna
     */
    public FmGlavna() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlSat = new javax.swing.JLabel();
        lblPoruka = new javax.swing.JLabel();
        btnOdjava = new javax.swing.JButton();
        jmbGlavniMeni = new javax.swing.JMenuBar();
        menuFaktura = new javax.swing.JMenu();
        miUnosNoveFakture = new javax.swing.JMenuItem();
        miPretragaFaktura = new javax.swing.JMenuItem();
        menuPoslovniPartneri = new javax.swing.JMenu();
        miUnosPoslovnihPartnera = new javax.swing.JMenuItem();
        miPrikazPoslovnihPartnera = new javax.swing.JMenuItem();
        menuProizvod = new javax.swing.JMenu();
        miUnosNovogProizvoda = new javax.swing.JMenuItem();
        miPrikazProizvoda = new javax.swing.JMenuItem();
        menuMesto = new javax.swing.JMenu();
        miUnosNovogMesta = new javax.swing.JMenuItem();
        miPrikazMesta = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("fmGlavna"); // NOI18N

        jlSat.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        lblPoruka.setText("jLabel3");

        btnOdjava.setText("Odjavi se");

        menuFaktura.setText("Faktura");

        miUnosNoveFakture.setText("Unos nove fakture");
        menuFaktura.add(miUnosNoveFakture);

        miPretragaFaktura.setText("Pretraga faktura");
        menuFaktura.add(miPretragaFaktura);

        jmbGlavniMeni.add(menuFaktura);

        menuPoslovniPartneri.setText("Poslovni partner");

        miUnosPoslovnihPartnera.setText("Unos novog partnera");
        menuPoslovniPartneri.add(miUnosPoslovnihPartnera);

        miPrikazPoslovnihPartnera.setText("Prikaz poslovnih partnera");
        menuPoslovniPartneri.add(miPrikazPoslovnihPartnera);

        jmbGlavniMeni.add(menuPoslovniPartneri);

        menuProizvod.setText("Proizvod");

        miUnosNovogProizvoda.setText("Unos novog proizvoda");
        menuProizvod.add(miUnosNovogProizvoda);

        miPrikazProizvoda.setText("Prikaz svih proizvoda");
        menuProizvod.add(miPrikazProizvoda);

        jmbGlavniMeni.add(menuProizvod);

        menuMesto.setText("Mesto");

        miUnosNovogMesta.setText("Unos novog mesta");
        menuMesto.add(miUnosNovogMesta);

        miPrikazMesta.setText("Prikaz svih mesta");
        menuMesto.add(miPrikazMesta);

        jmbGlavniMeni.add(menuMesto);

        setJMenuBar(jmbGlavniMeni);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlSat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 273, Short.MAX_VALUE)
                        .addComponent(btnOdjava))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblPoruka)))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblPoruka)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jlSat))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnOdjava)))
                .addContainerGap(205, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOdjava;
    private javax.swing.JLabel jlSat;
    private javax.swing.JMenuBar jmbGlavniMeni;
    private javax.swing.JLabel lblPoruka;
    private javax.swing.JMenu menuFaktura;
    private javax.swing.JMenu menuMesto;
    private javax.swing.JMenu menuPoslovniPartneri;
    private javax.swing.JMenu menuProizvod;
    private javax.swing.JMenuItem miPretragaFaktura;
    private javax.swing.JMenuItem miPrikazMesta;
    private javax.swing.JMenuItem miPrikazPoslovnihPartnera;
    private javax.swing.JMenuItem miPrikazProizvoda;
    private javax.swing.JMenuItem miUnosNoveFakture;
    private javax.swing.JMenuItem miUnosNovogMesta;
    private javax.swing.JMenuItem miUnosNovogProizvoda;
    private javax.swing.JMenuItem miUnosPoslovnihPartnera;
    // End of variables declaration//GEN-END:variables


    public JButton getBtnOdjava() {
        return btnOdjava;
    }

    public JMenuItem getMiPretragaFaktura() {
        return miPretragaFaktura;
    }

    public JMenuItem getMiPrikazMesta() {
        return miPrikazMesta;
    }

    public JMenuItem getMiPrikazPoslovnihPartnera() {
        return miPrikazPoslovnihPartnera;
    }

    public JMenuItem getMiPrikazProizvoda() {
        return miPrikazProizvoda;
    }

    public JMenuItem getMiUnosNoveFakture() {
        return miUnosNoveFakture;
    }

    public JMenuItem getMiUnosNovogMesta() {
        return miUnosNovogMesta;
    }

    public JMenuItem getMiUnosNovogProizvoda() {
        return miUnosNovogProizvoda;
    }

    public JMenuItem getMiUnosPoslovnihPartnera() {
        return miUnosPoslovnihPartnera;
    }

    public JLabel getLblPoruka() {
        return lblPoruka;
    }
}
