/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.glavna;

import forme.faktura.FmPretragaFaktura;
import forme.faktura.FmUnosFakture;
import forme.faktura.KontrolerKIUnosFakture;
import forme.korisnik.FmPrijavaKorisnika;
import forme.korisnik.KontrolerKIPrijavaKorisnika;
import forme.mesto.FmPrikazMesta;
import forme.mesto.FmUnosMesta;
import forme.partner.FmUnosPoslovnogPartnera;
import forme.partner.FmPrikazPartneraTabela;
import forme.partner.KontorlerKIUnosPoslovnogPartnera;
import forme.proizvod.FmPrikazProizvoda;
import forme.proizvod.FmUnosProizvoda;
import forme.proizvod.KontrolerKIUnosProizvoda;
import java.awt.BorderLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import kontroler.KontrolerKI;

/**
 *
 * @author student1
 */
public class FmGlavna extends javax.swing.JFrame {

    /**
     * Creates new form FmGlavna
     */
    public FmGlavna() {
        initComponents();
        setVisible(true);
        prijavaKorisnika();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlSat = new javax.swing.JLabel();
        lblPoruka = new javax.swing.JLabel();
        btnOdjava = new javax.swing.JButton();
        jmbGlavniMeni = new javax.swing.JMenuBar();
        menuFaktura = new javax.swing.JMenu();
        miUnosNoveFakture = new javax.swing.JMenuItem();
        miPretraga = new javax.swing.JMenuItem();
        menuPoslovniPartneri = new javax.swing.JMenu();
        miUnosPoslovnihPartnera = new javax.swing.JMenuItem();
        miPrikazPoslovnihPartnera = new javax.swing.JMenuItem();
        menuProizvod = new javax.swing.JMenu();
        miUnosNovogProizvoda = new javax.swing.JMenuItem();
        miPrikazProizvoda = new javax.swing.JMenuItem();
        menuMesto = new javax.swing.JMenu();
        miUnosNovogMesta = new javax.swing.JMenuItem();
        miPrikazMesta = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jlSat.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        lblPoruka.setText("jLabel3");

        btnOdjava.setText("Odjavi se");
        btnOdjava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdjavaActionPerformed(evt);
            }
        });

        menuFaktura.setText("Faktura");

        miUnosNoveFakture.setText("Unos nove fakture");
        miUnosNoveFakture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUnosNoveFaktureActionPerformed(evt);
            }
        });
        menuFaktura.add(miUnosNoveFakture);

        miPretraga.setText("Pretraga faktura");
        miPretraga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPretragaActionPerformed(evt);
            }
        });
        menuFaktura.add(miPretraga);

        jmbGlavniMeni.add(menuFaktura);

        menuPoslovniPartneri.setText("Poslovni partner");

        miUnosPoslovnihPartnera.setText("Unos novog partnera");
        miUnosPoslovnihPartnera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUnosPoslovnihPartneraActionPerformed(evt);
            }
        });
        menuPoslovniPartneri.add(miUnosPoslovnihPartnera);

        miPrikazPoslovnihPartnera.setText("Prikaz poslovnih partnera");
        miPrikazPoslovnihPartnera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPrikazPoslovnihPartneraActionPerformed(evt);
            }
        });
        menuPoslovniPartneri.add(miPrikazPoslovnihPartnera);

        jmbGlavniMeni.add(menuPoslovniPartneri);

        menuProizvod.setText("Proizvod");

        miUnosNovogProizvoda.setText("Unos novog proizvoda");
        miUnosNovogProizvoda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUnosNovogProizvodaActionPerformed(evt);
            }
        });
        menuProizvod.add(miUnosNovogProizvoda);

        miPrikazProizvoda.setText("Prikaz svih proizvoda");
        miPrikazProizvoda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPrikazProizvodaActionPerformed(evt);
            }
        });
        menuProizvod.add(miPrikazProizvoda);

        jmbGlavniMeni.add(menuProizvod);

        menuMesto.setText("Mesto");

        miUnosNovogMesta.setText("Unos novog mesta");
        miUnosNovogMesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUnosNovogMestaActionPerformed(evt);
            }
        });
        menuMesto.add(miUnosNovogMesta);

        miPrikazMesta.setText("Prikaz svih mesta");
        miPrikazMesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPrikazMestaActionPerformed(evt);
            }
        });
        menuMesto.add(miPrikazMesta);

        jmbGlavniMeni.add(menuMesto);

        setJMenuBar(jmbGlavniMeni);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlSat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 273, Short.MAX_VALUE)
                        .addComponent(btnOdjava))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblPoruka)))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblPoruka)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jlSat))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnOdjava)))
                .addContainerGap(205, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miUnosPoslovnihPartneraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUnosPoslovnihPartneraActionPerformed
        try {
            FmUnosPoslovnogPartnera f = new FmUnosPoslovnogPartnera(this, true);
            KontorlerKIUnosPoslovnogPartnera.kreirajPoslovnogPartnera(f);
            f.setVisible(true);
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greška", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_miUnosPoslovnihPartneraActionPerformed

    private void miPrikazPoslovnihPartneraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPrikazPoslovnihPartneraActionPerformed
        FmPrikazPartneraTabela f = new FmPrikazPartneraTabela(this, true);
        f.setVisible(true);
    }//GEN-LAST:event_miPrikazPoslovnihPartneraActionPerformed

    private void miUnosNovogMestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUnosNovogMestaActionPerformed
        FmUnosMesta f = new FmUnosMesta(this, true);
        f.setVisible(true);
    }//GEN-LAST:event_miUnosNovogMestaActionPerformed

    private void miUnosNoveFaktureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUnosNoveFaktureActionPerformed
        try {
            FmUnosFakture f = new FmUnosFakture(this, true);
            KontrolerKIUnosFakture.kreirajFakturu(f);
            f.setVisible(true);
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greška", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_miUnosNoveFaktureActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    }//GEN-LAST:event_formWindowOpened

    private void miPrikazMestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPrikazMestaActionPerformed
        FmPrikazMesta f = new FmPrikazMesta();
        JDialog dialog = new JDialog(this, true);
        dialog.setLayout(new BorderLayout());
        dialog.add(f, BorderLayout.CENTER);
        dialog.pack();
        dialog.setVisible(true);
    }//GEN-LAST:event_miPrikazMestaActionPerformed

    private void miUnosNovogProizvodaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUnosNovogProizvodaActionPerformed
        try {
            FmUnosProizvoda f = new FmUnosProizvoda(this, true);
            KontrolerKIUnosProizvoda.kreirajProizvod(f);
            f.setVisible(true);
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greška", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_miUnosNovogProizvodaActionPerformed

    private void miPrikazProizvodaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPrikazProizvodaActionPerformed
        FmPrikazProizvoda f = new FmPrikazProizvoda(this, true);
        f.setVisible(true);
    }//GEN-LAST:event_miPrikazProizvodaActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            KontrolerKI.prekiniKomunikaciju(this);
            //System.exit(0);
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greška", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_formWindowClosing

    private void miPretragaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPretragaActionPerformed
        FmPretragaFaktura f = new FmPretragaFaktura(this, true);
        f.setVisible(true);
    }//GEN-LAST:event_miPretragaActionPerformed

    private void btnOdjavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdjavaActionPerformed
        //setVisible(false);
        prijavaKorisnika();
        setVisible(true);
    }//GEN-LAST:event_btnOdjavaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FmGlavna().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOdjava;
    private javax.swing.JLabel jlSat;
    private javax.swing.JMenuBar jmbGlavniMeni;
    private javax.swing.JLabel lblPoruka;
    private javax.swing.JMenu menuFaktura;
    private javax.swing.JMenu menuMesto;
    private javax.swing.JMenu menuPoslovniPartneri;
    private javax.swing.JMenu menuProizvod;
    private javax.swing.JMenuItem miPretraga;
    private javax.swing.JMenuItem miPrikazMesta;
    private javax.swing.JMenuItem miPrikazPoslovnihPartnera;
    private javax.swing.JMenuItem miPrikazProizvoda;
    private javax.swing.JMenuItem miUnosNoveFakture;
    private javax.swing.JMenuItem miUnosNovogMesta;
    private javax.swing.JMenuItem miUnosNovogProizvoda;
    private javax.swing.JMenuItem miUnosPoslovnihPartnera;
    // End of variables declaration//GEN-END:variables

    private void prijavaKorisnika() {
        lblPoruka.setVisible(false);
        btnOdjava.setVisible(false);
        KontrolerKIPrijavaKorisnika.setKorisnik(null);
        FmPrijavaKorisnika dialog = new FmPrijavaKorisnika(this, true);
        dialog.setVisible(true);
        if (KontrolerKIPrijavaKorisnika.getKorisnik() != null) {
            lblPoruka.setText("Ulogovani ste kao: " + KontrolerKIPrijavaKorisnika.getKorisnik().getIme()
                    + " " + KontrolerKIPrijavaKorisnika.getKorisnik().getPrezime());
            lblPoruka.setVisible(true);
            btnOdjava.setVisible(true);
        } else {
            try {
                KontrolerKI.prekiniKomunikaciju(this);
                System.exit(0);
            } catch (Exception ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Greška", JOptionPane.ERROR_MESSAGE);
            }
            
        }

    }
}
