/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.partner;

import domen.Mesto;
import domen.PoslovniPartner;
import forme.mesto.KontrolorKIMesta;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author student1
 */
public class FmUnosPoslovnogPartnera extends javax.swing.JDialog {

    private final PoslovniPartner partner;

    /**
     * Creates new form FmUnosPoslovnogPartnera
     * @param parent
     * @param modal
     * @param model
     */
    public FmUnosPoslovnogPartnera(java.awt.Frame parent, boolean modal, PoslovniPartner model) {
        super(parent, modal);
        initComponents();
        this.partner = model;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbgPartner = new javax.swing.ButtonGroup();
        btnSnimi = new javax.swing.JButton();
        cbMesto = new javax.swing.JComboBox();
        txtBroj = new javax.swing.JTextField();
        txtUlica = new javax.swing.JTextField();
        txtKontakt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnIzmeni = new javax.swing.JButton();
        txtPib = new javax.swing.JFormattedTextField();
        txtNaziv = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Unos poslovnog partnera");

        btnSnimi.setText("Sačuvaj poslovnog partnera");

        cbMesto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Naziv:");

        jLabel3.setText("PIB:");

        jLabel7.setText("Kontakt:");

        jLabel4.setText("Ulica:");

        jLabel5.setText("Broj:");

        jLabel6.setText("Mesto:");

        btnIzmeni.setText("Izmeni poslovnog partnera");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUlica)
                            .addComponent(txtBroj)
                            .addComponent(cbMesto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtKontakt)
                            .addComponent(txtPib)
                            .addComponent(txtNaziv)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSnimi)
                        .addGap(27, 27, 27)
                        .addComponent(btnIzmeni)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtKontakt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtUlica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBroj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbMesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSnimi)
                    .addComponent(btnIzmeni))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnSnimi;
    private javax.swing.JComboBox cbMesto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.ButtonGroup jbgPartner;
    private javax.swing.JTextField txtBroj;
    private javax.swing.JTextField txtKontakt;
    private javax.swing.JFormattedTextField txtNaziv;
    private javax.swing.JFormattedTextField txtPib;
    private javax.swing.JTextField txtUlica;
    // End of variables declaration//GEN-END:variables

    public JComboBox getCbMesto() {
        return cbMesto;
    }

    public JButton getBtnIzmeni() {
        return btnIzmeni;
    }

    public JButton getBtnSnimi() {
        return btnSnimi;
    }

    public JTextField getTxtBroj() {
        return txtBroj;
    }

    public JTextField getTxtKontakt() {
        return txtKontakt;
    }

    public JTextField getTxtNaziv() {
        return txtNaziv;
    }

    public JFormattedTextField getTxtPib() {
        return txtPib;
    }

    public JTextField getTxtUlica() {
        return txtUlica;
    }
    
    public void postaviVrednosti(boolean izmena){
        try {
            List<Mesto> lm = KontrolorKIMesta.vratiMesta(this);
            cbMesto.removeAllItems();
            cbMesto.setModel(new DefaultComboBoxModel(lm.toArray()));
            cbMesto.setSelectedIndex(0);
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greška", JOptionPane.ERROR_MESSAGE);
        }
        if (izmena) {
            getTxtNaziv().setText(partner.getNaziv());
            getTxtPib().setText(partner.getPib());
            getTxtKontakt().setText(partner.getKontakt());
            getTxtUlica().setText(partner.getAdresa().getUlica());
            getTxtBroj().setText(partner.getAdresa().getBroj());
            getCbMesto().setSelectedItem(partner.getAdresa().getMesto());
            getBtnSnimi().setEnabled(false);
            getBtnIzmeni().setEnabled(true);
        } else {
            btnIzmeni.setEnabled(false);
        }
    }
}
