/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.proizvod;

import domen.JedMere;
import domen.Proizvod;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author Jelena
 */
public class FmUnosProizvoda extends javax.swing.JDialog {

    private Proizvod proizvod;

    /**
     * Creates new form FmUnosProizvoda
     */
    public FmUnosProizvoda(java.awt.Frame parent, boolean modal, Proizvod model) {
        super(parent, modal);
        initComponents();
        proizvod = model;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnSacuvaj = new javax.swing.JButton();
        txtNaziv = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCena = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbJedMere = new javax.swing.JComboBox();
        btnIzmeniProizvod = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Unos novog proizvoda");

        jLabel1.setText("Naziv:");

        btnSacuvaj.setText("Sačuvaj proizvod");

        jLabel2.setText("Cena:");

        jLabel3.setText("Jedinica mere:");

        cbJedMere.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnIzmeniProizvod.setText("Izmeni proizvod");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSacuvaj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnIzmeniProizvod))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtCena)
                            .addComponent(txtNaziv)
                            .addComponent(cbJedMere, 0, 231, Short.MAX_VALUE))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(cbJedMere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSacuvaj)
                    .addComponent(btnIzmeniProizvod))
                .addContainerGap(124, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeniProizvod;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JComboBox cbJedMere;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtCena;
    private javax.swing.JTextField txtNaziv;
    // End of variables declaration//GEN-END:variables

    void popuniPodatke(boolean izmena) {
        cbJedMere.setModel(new DefaultComboBoxModel(JedMere.values()));
        cbJedMere.setSelectedIndex(0);
        if(izmena){
            txtNaziv.setText(proizvod.getNaziv());
            txtCena.setText(String.valueOf(proizvod.getCena()));
            cbJedMere.setSelectedItem(proizvod.getJedinicaMere());
            btnSacuvaj.setEnabled(false);
            btnIzmeniProizvod.setEnabled(true);
        } else {
            btnIzmeniProizvod.setEnabled(false);
        }
    }

    public JButton getBtnIzmeniProizvod() {
        return btnIzmeniProizvod;
    }

    public JButton getBtnSacuvaj() {
        return btnSacuvaj;
    }

    public JComboBox getCbJedMere() {
        return cbJedMere;
    }

    public JTextField getTxtCena() {
        return txtCena;
    }

    public JTextField getTxtNaziv() {
        return txtNaziv;
    }
}
