/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.faktura;

import domen.Faktura;
import domen.Proizvod;
import forme.faktura.model.ModelTabeleStavkaFakture;
import forme.partner.KontrolerKIPrikazPoslovnihPartnera;
import forme.proizvod.KontrolerKIPrikazProizvoda;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.DefaultCellEditor;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Jelena
 */
public class FmUnosFakture extends javax.swing.JDialog {

    private Faktura faktura;

    /**
     * Creates new form FmUnosFakture
     */
    public FmUnosFakture(java.awt.Frame parent, boolean modal, Faktura model) {
        super(parent, modal);
        initComponents();
        faktura = model;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtBrojFakture = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDatum = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbPoslovniPartner = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStavkeFakture = new javax.swing.JTable();
        btnDodajStavku = new javax.swing.JButton();
        btnSacuvaj = new javax.swing.JButton();
        btnObradi = new javax.swing.JButton();
        btnIzmeni = new javax.swing.JButton();
        btnStorniraj = new javax.swing.JButton();
        labelUkupanIznos = new javax.swing.JLabel();
        txtUkupnaVrednost = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtBrojOtpremnice = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtOsnovica = new javax.swing.JTextField();
        txtPdv = new javax.swing.JTextField();
        btnObrisiStavku = new javax.swing.JButton();
        checkObradjena = new javax.swing.JCheckBox();
        checkStornirana = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Broj fakture:");

        jLabel2.setText("Datum (dd/MM/yyyy):");

        jLabel3.setText("Poslovni partner:");

        cbPoslovniPartner.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tblStavkeFakture.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblStavkeFakture);

        btnDodajStavku.setText("+");

        btnSacuvaj.setText("Sačuvaj");

        btnObradi.setText("Obradi");

        btnIzmeni.setText("Izmeni");

        btnStorniraj.setText("Storniraj");

        labelUkupanIznos.setText("Ukupna vrednost:");

        txtUkupnaVrednost.setEditable(false);

        jLabel4.setText("Broj otpremnice:");

        jLabel5.setText("Poreska osnovica:");

        jLabel6.setText("PDV:");

        txtOsnovica.setEditable(false);

        txtPdv.setEditable(false);

        btnObrisiStavku.setText("-");

        checkObradjena.setText("Obrađena");
        checkObradjena.setEnabled(false);

        checkStornirana.setText("Stornirana");
        checkStornirana.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnIzmeni)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnObradi)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnStorniraj))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtDatum, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtBrojOtpremnice, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtBrojFakture, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbPoslovniPartner, 0, 205, Short.MAX_VALUE))
                                        .addGap(59, 59, 59)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(checkObradjena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(checkStornirana, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(labelUkupanIznos))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtOsnovica)
                            .addComponent(txtPdv)
                            .addComponent(txtUkupnaVrednost, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDodajStavku)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnObrisiStavku, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnIzmeni, btnObradi, btnSacuvaj, btnStorniraj});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDodajStavku, btnObrisiStavku});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBrojFakture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtBrojOtpremnice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkObradjena))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkStornirana))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbPoslovniPartner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtOsnovica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDodajStavku)
                    .addComponent(btnObrisiStavku))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPdv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUkupanIznos)
                    .addComponent(txtUkupnaVrednost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStorniraj)
                    .addComponent(btnSacuvaj)
                    .addComponent(btnObradi)
                    .addComponent(btnIzmeni))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajStavku;
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnObradi;
    private javax.swing.JButton btnObrisiStavku;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JButton btnStorniraj;
    private javax.swing.JComboBox cbPoslovniPartner;
    private javax.swing.JCheckBox checkObradjena;
    private javax.swing.JCheckBox checkStornirana;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelUkupanIznos;
    private javax.swing.JTable tblStavkeFakture;
    private javax.swing.JTextField txtBrojFakture;
    private javax.swing.JTextField txtBrojOtpremnice;
    private javax.swing.JTextField txtDatum;
    private javax.swing.JTextField txtOsnovica;
    private javax.swing.JTextField txtPdv;
    private javax.swing.JTextField txtUkupnaVrednost;
    // End of variables declaration//GEN-END:variables

    public void setSacuvana() {
        btnSacuvaj.setEnabled(false);
        btnIzmeni.setEnabled(true);
        btnStorniraj.setEnabled(false);
        btnObradi.setEnabled(true);
    }

    public void setObradjena() {
        btnSacuvaj.setEnabled(false);
        btnIzmeni.setEnabled(false);
        btnStorniraj.setEnabled(true);
        btnObradi.setEnabled(false);
        btnDodajStavku.setEnabled(false);
        btnObrisiStavku.setEnabled(false);
        
        checkObradjena.setSelected(true);
        
        txtBrojFakture.setEditable(false);
        txtBrojOtpremnice.setEditable(false);
        txtDatum.setEditable(false);
        
        cbPoslovniPartner.setEnabled(false);
        
        tblStavkeFakture.setEnabled(false);
    }

    public void setStornirana() {
        btnSacuvaj.setEnabled(false);
        btnIzmeni.setEnabled(false);
        btnStorniraj.setEnabled(false);
        btnObradi.setEnabled(false);
        btnDodajStavku.setEnabled(false);
        btnObrisiStavku.setEnabled(false);
        
        checkObradjena.setSelected(true);
        checkStornirana.setSelected(true);
        
        txtBrojFakture.setEditable(false);
        txtBrojOtpremnice.setEditable(false);
        txtDatum.setEditable(false);
        
        cbPoslovniPartner.setEnabled(false);
        
        tblStavkeFakture.setEnabled(false);
    }

    public void setKreirana() {
        btnSacuvaj.setEnabled(true);
        btnIzmeni.setEnabled(false);
        btnStorniraj.setEnabled(false);
        btnObradi.setEnabled(false);
    }

    void popuniPodatke(boolean izmena) {
        try {
            tblStavkeFakture.setModel(new ModelTabeleStavkaFakture(faktura));
            cbPoslovniPartner.setModel(new DefaultComboBoxModel(KontrolerKIPrikazPoslovnihPartnera.vratiPoslovnePartnere(this).toArray()));
            List<Proizvod> proizvodi = KontrolerKIPrikazProizvoda.vratiProizvode(this);
            JComboBox comboBoxProizvodi = new JComboBox(new DefaultComboBoxModel(proizvodi.toArray()));
            TableColumnModel tcm = tblStavkeFakture.getColumnModel();
            TableColumn tc = tcm.getColumn(1);
            tc.setCellEditor(new DefaultCellEditor(comboBoxProizvodi));
            setKreirana();
            if(izmena){
                txtBrojFakture.setText(faktura.getBrojFakture());
                txtBrojOtpremnice.setText(faktura.getBrojOtpremnice());
                txtDatum.setText(new SimpleDateFormat("dd/MM/yyyy").format(faktura.getDatum()));
                tblStavkeFakture.setModel(new ModelTabeleStavkaFakture(faktura));
                cbPoslovniPartner.setModel(new DefaultComboBoxModel(KontrolerKIPrikazPoslovnihPartnera.vratiPoslovnePartnere(this).toArray()));
                cbPoslovniPartner.setSelectedItem(faktura.getPoslovniPartner());
                checkObradjena.setSelected(faktura.isObradjena());
                checkStornirana.setSelected(faktura.isStornirana());
                txtOsnovica.setText(((ModelTabeleStavkaFakture) tblStavkeFakture.
                            getModel()).vratiPoreskuOsnovicu());
                txtPdv.setText(((ModelTabeleStavkaFakture) tblStavkeFakture.
                            getModel()).vratiPDV());
                txtUkupnaVrednost.setText(((ModelTabeleStavkaFakture) tblStavkeFakture.
                            getModel()).vratiUkupnuVrednostFakture(txtOsnovica, txtPdv));
                setSacuvana();
                if(faktura.isStornirana())
                    setStornirana();
                else if(faktura.isObradjena())
                    setObradjena();
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greška", JOptionPane.ERROR_MESSAGE);
        }
    }

    void setFaktura(Faktura f) {
        faktura = f;
    }
    
    public Faktura getFaktura(){
        return faktura;
    }

    public JButton getBtnDodajStavku() {
        return btnDodajStavku;
    }

    public JButton getBtnIzmeni() {
        return btnIzmeni;
    }

    public JButton getBtnObradi() {
        return btnObradi;
    }

    public JButton getBtnObrisiStavku() {
        return btnObrisiStavku;
    }

    public JButton getBtnSacuvaj() {
        return btnSacuvaj;
    }

    public JButton getBtnStorniraj() {
        return btnStorniraj;
    }

    public JComboBox getCbPoslovniPartner() {
        return cbPoslovniPartner;
    }

    public JCheckBox getCheckObradjena() {
        return checkObradjena;
    }

    public JCheckBox getCheckStornirana() {
        return checkStornirana;
    }

    public JTable getTblStavkeFakture() {
        return tblStavkeFakture;
    }

    public JTextField getTxtBrojFakture() {
        return txtBrojFakture;
    }

    public JTextField getTxtBrojOtpremnice() {
        return txtBrojOtpremnice;
    }

    public JTextField getTxtDatum() {
        return txtDatum;
    }

    public JTextField getTxtOsnovica() {
        return txtOsnovica;
    }

    public JTextField getTxtPdv() {
        return txtPdv;
    }

    public JTextField getTxtUkupnaVrednost() {
        return txtUkupnaVrednost;
    }
}
